language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm ci
  - npm install --global expo-cli
  - npm install cypress --save-dev
  - npm test
  - npm run predeploy
after_success:
  - npm install -g firebase-tools
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive --only hosting