language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm ci
  - npm install --global expo-cli
  - npm install cypress --save-dev
  - npm test
  - npm run test:ci
  - npm run predeploy
after_success:
  - npm install -g firebase-tools
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive --only hosting
# install: travis_wait mvn install
# language: node_js
# node_js:
#   - "stable"
# addons:
#   apt:
#     packages:
#       # needed by Cypress, not in Ubuntu 16+ by default
#       - libgconf-2-4
# cache:
#   directories:
#   - node_modules
#   # folder with Cypress binary
#   - ~/.cache
# script:
#   - npm run test:ci
#   - npm run build